// <auto-generated />
namespace MailSender.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class user_smtp_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_smtp_data));
        
        string IMigrationMetadata.Id
        {
            get { return "202102091508078_user_smtp_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
